spring:
  datasource:
    url: jdbc:h2:mem:hieroglyphsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: admin
    driverClassName: org.h2.Driver

  h2:
    # http://localhost:8080/h2-console
    console:
       enabled: true
       path: /h2-console
       settings.trace: false
       settings.web-allow-others: false
       
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

    # création schéma par hibernate puis injection data.sql
    defer-datasource-initialization: true

    open-in-view: false

  cache:
    jcache:
      config: classpath:ehcache.xml

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    # mot de passe passé en paramètre lors exécution 
    password: ${my.password}
    virtual-host: mspoc

# paramètres queues
mspoc1:
  rabbitmq:
    in:
      consumerQueueName: "q1"
    out:
      exchange: "q2_ex"
      routingKey: "message.q2"



    